Sprint1/step2
Renatskiy/react-burger pull request #2
Opened 2022-10-07 06:16 UTC by Renatskiy

Правки после первого шага

2022-10-07 18:48 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

- Почти все замечания с прошлого ревью, были исправлены.

### **Но есть несколько новых замечаний, которые нужно исправить:**

- не нужно отправлять исправления, каждый раз в новом Pull Request, просто отправляйте ссылку на этот же Pull Request.

- Удалите все неиспользуемые файлы.

- не для всех компонентов описаны PropTypes.

- для всех необходимых для отображения компонента пропсов в propTypes должен задаваться `.isRequired`.

- Верстка не соответствует макету:
  - в компоненте burgerConstructor, булки должны стоять на месте. вот пример на видео: https://disk.yandex.ru/i/gFVvnVBJrpPczA

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-10-07 18:48 UTC, ArslanDev666 commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +          )}
**Надо исправить:** поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте.

2022-10-07 18:48 UTC, ArslanDev666 commented on src/components/Main/Main.jsx
> +  }
**Можно лучше:** Здесь и во всём проекте, если вы не передаёте пропсы в компонент, то можно не писать конструктор.

2022-10-07 18:48 UTC, ArslanDev666 commented on src/components/AppMenuItem/AppMenuItem.jsx
> +class AppMenuItem extends React.Component {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-07 18:48 UTC, ArslanDev666 commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +};
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2022-10-07 18:48 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    const typesIngredient = sortItems.reduce((acc, val) => {
**Можно лучше:** Неплохое решение, но представим ситуацию, что у вас около 15 разных категорий ингредиентов. Тогда вам придеться очень много условий писать, что существенно замедлит работую приложения. Вот как можно сделать это проще.
Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.
```
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

2022-10-07 18:48 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +                onClick={setCurrent}
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2022-10-07 18:48 UTC, ArslanDev666 commented on src/components/BurgerIngredientsSection/BurgerIngredientsSection.jsx
> +export default class BurgerIngredientSection extends React.Component {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-07 18:48 UTC, ArslanDev666 commented on src/components/Main/Main.jsx
> +export default class Main extends React.Component {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-08 18:41 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

- Почти все замечания с прошлого ревью, были исправлены.
- Напоминаю, что работа будет принята, только после того как будут исправлены все замечания `Надо исправить`.

### **Но есть несколько новых замечаний, которые нужно исправить:**

- В некоторых местах в propTypes описаны не все пропсы.

- Исправьте ошибки в консоли. 
   
   ![image](https://user-images.githubusercontent.com/70164458/194722611-7b57964a-aa06-4325-8c5a-f2a98084f7ca.png)
 

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-08 18:41 UTC, ArslanDev666 commented on src/components/AppMenuItem/AppMenuItem.jsx
> +AppMenuItem.propTypes = {
**Надо исправить:** Описаны не все передаваемые пропсы.

2022-10-08 18:41 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  ]
**Надо исправить:** не нужно делать дополнительный массив, middleItems, это уже массив.

2022-10-08 18:41 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                text={getName(bun.name, "top")}
**Можно лучше:** тут можно сразу написать `bun.name` + "Вверх"`

2022-10-08 18:41 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                    }
**Надо исправить:** Это условие всегда будет выполняться, т.к мы сделали фильтр. Поэтому лучше убрать условие.

2022-10-08 18:41 UTC, ArslanDev666 commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +          )}
Замечание не исправлено.

2022-10-08 18:41 UTC, ArslanDev666 commented on src/components/BurgerIngredientsSection/BurgerIngredientsSection.jsx
> +BurgerIngredientSection.propTypes = {
**Надо исправить:** Описаны не все передаваемые пропсы.

2022-10-08 18:41 UTC, ArslanDev666 commented on src/components/Main/Main.jsx
> +export default class Main extends React.Component {
Замечание не исправлено.

2022-10-08 21:23 UTC, ArslanDev666 requested changes
Замечания, которые были отмечены в коде, до сих пор не исправлены, работа отклонена на ревью (без потери итерации). Проверьте еще раз начиная с 1 ревью этого пулл реквеста.

2022-10-09 08:40 UTC, Renatskiy commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +          )}
готово

2022-10-09 08:40 UTC, Renatskiy commented on src/components/Main/Main.jsx
> +  }
готово

2022-10-09 08:40 UTC, Renatskiy commented on src/components/AppMenuItem/AppMenuItem.jsx
> +class AppMenuItem extends React.Component {
готово

2022-10-09 08:41 UTC, Renatskiy commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +};
готово

2022-10-09 09:49 UTC, Renatskiy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    const typesIngredient = sortItems.reduce((acc, val) => {
готово, но у меня не получилось именно с useMemo. Сделал фильтрованные массивы по конкретным типам
В будущем, как разберусь с применением хуков, обязательно оптимизирую

2022-10-09 09:49 UTC, Renatskiy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +                onClick={setCurrent}
готово

2022-10-09 09:50 UTC, Renatskiy commented on src/components/BurgerIngredientsSection/BurgerIngredientsSection.jsx
> +export default class BurgerIngredientSection extends React.Component {
готово

2022-10-09 09:50 UTC, Renatskiy commented on src/components/Main/Main.jsx
> +export default class Main extends React.Component {
готово

2022-10-09 09:50 UTC, Renatskiy commented on src/components/AppMenuItem/AppMenuItem.jsx
> +AppMenuItem.propTypes = {
готово

2022-10-09 09:50 UTC, Renatskiy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                    }
убрал

2022-10-09 10:11 UTC, Renatskiy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    const typesIngredient = sortItems.reduce((acc, val) => {
готово

2022-10-10 08:23 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодцы! Можете приступать к финальной части задания.**

2022-10-10 09:25 UTC, merged