второй этап
Renatskiy/react-burger pull request #3
Opened 2022-10-11 14:30 UTC by Renatskiy

Второй этап

2022-10-11 20:30 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

### **Но есть несколько замечаний, которые нужно исправить:**

- Перед проверкой убедитесь, что работа не содержит неиспользуемый код.

- Вынесите магическое значение 27 в именованную константу

- Рендерите компонент попапа только если он нужен на странице (подробнее отмечено в коде).

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-11 20:30 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +  }, []);
**Можно лучше:** Тут можно не использовать useCallback, достаточно это всё внести в useEffect, и написать вот так:

```js
  useEffect(() => {
    fetchRequest("/ingredients")
      .then(setData)
      .catch(() => alert("Во время загрузки ингредиентов произошла ошибка."))
      .finally(() => setIngredientsLoading(false));
  }, []);

```

2022-10-11 20:30 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +      setData([...data, ...res.data]);
**Можно лучше:** не совсем понятно, зачем вы тут остаточные параметры используете (`...data`). Запрос будет выполняться 1 раз. А изначально у вас в стейте пустой массив. Поэтому лучше будет это убрать, и оставить просто setDate(res.data).Или код, который я продемонстрировал ниже.

2022-10-11 20:30 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const middleItems = orders.filter((x) => x.type !== "bun");
**Можно лучше:** Это всё стоит обернуть в useMemo.

2022-10-11 20:30 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      <Modal show={show} onClose={() => setShow(false)}>
**Можно лучше:** Вынесите обработчик событий в отдельную функцию.

2022-10-11 20:30 UTC, ArslanDev666 commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +      <Modal show={show} onClose={() => setShow(false)}>
**Можно лучше:** Вынесите обработчик событий в отдельную функцию.

2022-10-11 20:30 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +    if ((e.charCode || e.keyCode) === 27) {
**Надо исправить**

вынесите магическое значение 27 в именованную константу `const ECK_KEYCODE = 27`

2022-10-11 20:30 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +  const closeOnEsc = (e) => {
**Можно лучше:** Лучше занести функцию в useEffect. тогда она не будет создаваться при каждом ререндере.

2022-10-11 20:30 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +  };
**можно лучше:** Можно не создавать дополнительную функцию. Чуть передвиньте modalOverlay, и поставьте на onClick - закрытие попапа. Вот так
```js
<>
      <div className={styles.modal}>
      // {...}
      </div>
      <ModalOverlay onClick={onClose} />
<>
```

И тогда у нас отпадёт надобность в еще нескольких обработчиках событий, которые расположены ниже.

2022-10-11 20:30 UTC, ArslanDev666 commented on src/components/Modal/Modal.jsx
> +    show &&
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```
{isOpen && (
    компонент открываемого попапа
)}
``

2022-10-12 05:03 UTC, Renatskiy commented on src/components/App/App.jsx
> +  }, []);
готово

2022-10-12 05:04 UTC, Renatskiy commented on src/components/App/App.jsx
> +      setData([...data, ...res.data]);
готово

2022-10-12 05:10 UTC, Renatskiy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const middleItems = orders.filter((x) => x.type !== "bun");
done

2022-10-12 05:13 UTC, Renatskiy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      <Modal show={show} onClose={() => setShow(false)}>
done

2022-10-12 05:14 UTC, Renatskiy commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +      <Modal show={show} onClose={() => setShow(false)}>
done

2022-10-12 05:15 UTC, Renatskiy commented on src/components/Modal/Modal.jsx
> +    if ((e.charCode || e.keyCode) === 27) {
done

2022-10-12 05:32 UTC, Renatskiy commented on src/components/Modal/Modal.jsx
> +  const closeOnEsc = (e) => {
done

2022-10-12 06:45 UTC, Renatskiy commented on src/components/Modal/Modal.jsx
> +  const closeOnEsc = (e) => {
done

2022-10-12 06:45 UTC, Renatskiy commented on src/components/Modal/Modal.jsx
> +  };
done

2022-10-12 06:59 UTC, Renatskiy commented on src/components/Modal/Modal.jsx
> +    show &&
done

2022-10-12 22:30 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодцы! Работа принята!**

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2022-10-12 22:31 UTC, ArslanDev666 commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +      )}
**Можно лучше:** Лучше вынести в компонент BurgerIngredients, А то у вас теперь в каждом компоненте есть рендер попапа, что не есть хорошо. т.к теперь приложение занимает больше памяти, а значит ему нужно больше времени, чтобы всё отрендерить.

2022-10-17 06:02 UTC, merged