sprint2-step2
Renatskiy/react-burger pull request #5
Opened 2022-10-23 14:16 UTC by Renatskiy

2022-10-23 15:11 UTC, andryxxa93 requested changes
Хорошая работа! Вы неплохо разобрались с redux. Правильно организовали и подключили редьюсеры и экшены. Круто, что вы реализовали автоскролл по категориям!  
Есть два замечания, которые необходимо исправить чтобы работа была принята - 
1. У всех запросов к api должно быть три экшена - на сам запрос (_REQUEST), на его успешный исход (_SUCCESS) и на случай ошибки (_FAILURE). Для получения ингредиентов и номера заказа нужно сделать так. Более подробно смотрите комментарий в pull-request.
2. Есть небольшой баг с перемещением внутри конструктора, при перемещении ингредиента соседние элементы так же меняются местами -  
https://user-images.githubusercontent.com/60173362/197399885-5a77c10a-33e5-4cfd-b176-86587d991d8b.mov

Удачных правок!

2022-10-23 15:11 UTC, andryxxa93 commented on src/services/actions/order/order-actions.js
> +        console.error("Не получилось оформить заказ");
**Необходимо исправить**
У ордера, как и у всех запросов к api должно быть 3 экшена - REQUEST, SUCCESS и FAILURE. При SUCESS нужно записывать номер заказа, а при FAILURE удалять старый номер (чтобы пользователь не увидел случайно его) и выводить ошибку - последнее не обязательно, но для пользователя будет удобно. То же касается и запроса на получение ингредиентов.

2022-10-23 16:34 UTC, Renatskiy commented on src/services/actions/order/order-actions.js
> +        console.error("Не получилось оформить заказ");
готово. Если я правильно понял вашу мысль)

2022-10-24 07:41 UTC, andryxxa93 requested changes
Переименуйте экшены ордeра, как написано в комментарии (https://github.com/Renatskiy/react-burger/pull/5#discussion_r1002965139) -  и добавьте сброс списка ингредиентов при ошибке запроса.

2022-10-24 07:41 UTC, andryxxa93 commented on src/services/reducers/order.js
>    orderNumber: 0,
**Можно лучше**
OrderNumber наверное будет лучше изначально делать undefined или null.

2022-10-24 07:41 UTC, andryxxa93 commented on src/services/actions/order/order-actions.js
> +          dispatch({ type: SUCCESS, payload: order?.number });
**Ноебходимо исправить**
Прошу прощения, мне стоило яснее выразиться - экшены необходимо называть так `ORDER_SUCCESS` `ORDER__FAILURE` иначе не всегда будет понятно к чему конкретно относится этот экшн, особенно когда запросов будет много.

2022-10-24 08:03 UTC, Renatskiy commented on src/services/reducers/order.js
>    orderNumber: 0,
готово

2022-10-24 08:03 UTC, Renatskiy commented on src/services/actions/order/order-actions.js
> +          dispatch({ type: SUCCESS, payload: order?.number });
готово

2022-10-24 09:58 UTC, andryxxa93 approved these changes
Всё отлично! Работа принята. Удачного продолжения обучения!

2022-10-24 10:11 UTC, merged