Sprint3/step1
Renatskiy/react-burger pull request #6
Opened 2022-11-04 08:27 UTC by Renatskiy

2022-11-04 09:38 UTC, andryxxa93 requested changes
Отличная работа! Основной функционал работает верно. Понравилось, что вы обрабатываете ситуацию когда токен может протухнуть. Код написан чисто и понятно. 
Есть несколько замечаний, которые необходимо исправить, чтобы работа была принята.
1. При logout происходит ошибка. Что-то не так с экшеном. 
<img width="1440" alt="Снимок экрана 2022-11-04 в 11 46 21" src="https://user-images.githubusercontent.com/60173362/199930772-5f84c6e7-b6c9-4073-b9c5-b09cd97060c2.png">
2. После успешной регистрации необходимо переходить на главную страницу. Иначе сейчас пользователь остается на странице регистрации и не понятно регистрация получилась или нет.
3. Не работает восстановление пароля. Почему-то не получается ввести в инпут пароль. Хотя в код восстановления можно. 

https://user-images.githubusercontent.com/60173362/199932193-6a562ba1-e6e3-4cc0-a6ae-26fc11dc46fd.mov

4. Кнопка отмены и сохранения должны становится активными только после того как пользователь изменил данные в форме данных профиля.
5. Вынесите время жизни токена в отдельную константу.

Удачных правок!

2022-11-04 09:38 UTC, andryxxa93 commented on src/api/index.js
> +    if (token !== "") {
**Можно лучше**
Тут можно просто 
`if (token)`
так как пустая строка это ложноподобное значение

2022-11-04 09:38 UTC, andryxxa93 commented on src/components/RegisterForm/index.jsx
> +    console.log(res);
**Можно лучше**
Консоль обычно нужна только для процесса разработки, перед созданием pull-request её необходимо удалять.

2022-11-04 09:38 UTC, andryxxa93 commented on src/services/actions/user/user-actions.js
> +        console.log(error, "error");
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше показывать пользователю, например в модальном окне, чтобы он понимал, что происходит.

2022-11-04 13:38 UTC, Renatskiy commented
Подскажите пожалуйста по поводу выноса в константу жизни токена. Я не понял полностью где это сделать и каким образом. Сделал , как понял, но может быть неправильно)

2022-11-05 05:48 UTC, andryxxa93 commented
> Подскажите пожалуйста по поводу выноса в константу жизни токена. Я не понял полностью где это сделать и каким образом. Сделал , как понял, но может быть неправильно)

Время жизни токена сейчас 20 минут. Вот это значение стоит вынести в константу, чтобы если в будущем что-то измениться, то можно было в одном месте поменять и всё.
Вот примерно так

```
export const TOKEN_EXPIRES = 20 * 60 * 1000;
 const time = new Date(new Date().getTime() + TOKEN_EXPIRES);
```


Вообще сам подсчет времени истечения токена можно вынести в функцию, не то у вас код повторяется три раза.

```
const getTokenExpiresTime = () => new Date(new Date().getTime() + TOKEN_EXPIRES);
const time = getTokenExpiresTime();
```

2022-11-05 05:52 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2022-11-24 05:46 UTC, merged